import AutoPaginatedTable from "./AutoPaginatedTable";
import { Icon } from "@iconify/react";

const Substitutions = <AutoPaginatedTable
  header={[
    { title: "", icon: <Icon icon="mdi:clock" /> },
    { title: "Tanár", icon: <Icon icon="mdi:account" /> },
    { title: "Helyettes", icon: <Icon icon="mdi:account-group" /> },
    { title: "Osztály", icon: <Icon icon="mdi:school" /> },
    { title: "Terem", icon: <Icon icon="mdi:location" /> },
    { title: "", icon: <Icon icon="material-symbols:merge" /> },
  ]}
  data={[
    {
      lesson: 1,
      className: "9.D",
      classroom: "A109",
      teacher: "Kovács Béla",
      missing: "Nagy János",
      consolidated: false,
    },
    {
      lesson: 2,
      className: "10.A",
      classroom: "B202",
      teacher: "Szabó Anna",
      missing: "Kiss Péter",
      consolidated: true,
    },
    {
      lesson: 3,
      className: "11.B",
      classroom: "C303",
      teacher: "Tóth Gábor",
      missing: "Varga László",
      consolidated: false,
    },
    {
      lesson: 4,
      className: "12.C",
      classroom: "D404",
      teacher: "Németh Zoltán, Horváth Tamás, Kovács Béla, Szabó Anna",
      missing: "Horváth Tamás, Kovács Béla, Szabó Anna, Nagy János",
      consolidated: true,
    },
    {
      lesson: 5,
      className: "9.A",
      classroom: "E505",
      teacher: "Balogh István",
      missing: "Kovács László",
      consolidated: false,
    },
    {
      lesson: 6,
      className: "10.B",
      classroom: "F606",
      teacher: "Farkas János",
      missing: "Molnár Ferenc",
      consolidated: true,
    },
    {
      lesson: 7,
      className: "11.C",
      classroom: "G707",
      teacher: "Papp Zsuzsanna",
      missing: "Szabó Katalin",
      consolidated: false,
    },
    {
      lesson: 8,
      className: "12.D",
      classroom: "H808",
      teacher: "Kiss Lajos, Nagy István, Tóth János, Balogh Zoltán",
      missing: "Nagy István, Tóth János, Balogh Zoltán, Kovács László",
      consolidated: true,
    },
    {
      lesson: 9,
      className: "9.B",
      classroom: "I909",
      teacher: "Varga Mária",
      missing: "Tóth János",
      consolidated: false,
    },
    {
      lesson: 0,
      className: "10.C",
      classroom: "J1010",
      teacher: "Horváth Péter",
      missing: "Balogh Zoltán",
      consolidated: true,
    },
    {
      lesson: 1,
      className: "11.D",
      classroom: "K1111",
      teacher: "Molnár János",
      missing: "Farkas László",
      consolidated: false,
    },
    {
      lesson: 2,
      className: "12.A",
      classroom: "L1212",
      teacher: "Szabó Gábor",
      missing: "Papp István",
      consolidated: true,
    },
    {
      lesson: 3,
      className: "9.C",
      classroom: "M1313",
      teacher: "Kovács Anna",
      missing: "Németh László",
      consolidated: false,
    },
    {
      lesson: 4,
      className: "10.D",
      classroom: "N1414",
      teacher: "Tóth István, Varga Péter, Nagy János, Szabó Anna",
      missing: "Varga Péter, Nagy János, Szabó Anna, Kovács Béla",
      consolidated: true,
    },
    {
      lesson: 5,
      className: "11.A",
      classroom: "O1515",
      teacher: "Nagy Zoltán",
      missing: "Horváth Gábor",
      consolidated: false,
    },
    {
      lesson: 6,
      className: "12.B",
      classroom: "P1616",
      teacher: "Balogh Katalin",
      missing: "Kiss János",
      consolidated: true,
    },
    {
      lesson: 7,
      className: "9.D",
      classroom: "Q1717",
      teacher: "Farkas Péter",
      missing: "Molnár Zoltán",
      consolidated: false,
    },
    {
      lesson: 8,
      className: "10.A",
      classroom: "R1818",
      teacher: "Papp László",
      missing: "Szabó István",
      consolidated: true,
    },
    {
      lesson: 9,
      className: "11.B",
      classroom: "S1919",
      teacher: "Németh Anna",
      missing: "Tóth Zoltán",
      consolidated: false,
    },
    {
      lesson: 0,
      className: "12.C",
      classroom: "T2020",
      teacher: "Kiss Péter, Varga Gábor, Horváth Tamás, Kovács Béla",
      missing: "Varga Gábor, Horváth Tamás, Kovács Béla, Szabó Anna",
      consolidated: true,
    },
    {
      lesson: 1,
      className: "9.A",
      classroom: "U2121",
      teacher: "Horváth János",
      missing: "Balogh István",
      consolidated: false,
    },
  ]}
  tableHeight={410}
  cycleInterval={5000} />;

export default Substitutions;