[kiosk]
petriktv-b ansible_host=10.1.0.68 ansible_user=root

[kiosk:vars]
ssh_public_key="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBNJJwi4lxbR4yNXeMd1Tr8EWkXLypYsnrtx6V4vmQvU"
github_repo=nemvince/petriktv